// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlataformaEducacaoOnline.Conteudos.Data;

#nullable disable

namespace PlataformaEducacaoOnline.Conteudos.Data.Migrations
{
    [DbContext(typeof(ConteudoDbContext))]
    partial class ConteudoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("PlataformaEducacaoOnline.Conteudos.Domain.Entities.Aula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CursoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("plataformaead_aulas", (string)null);
                });

            modelBuilder.Entity("PlataformaEducacaoOnline.Conteudos.Domain.Entities.Curso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataConclusao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("plataformaead_cursos", (string)null);
                });

            modelBuilder.Entity("PlataformaEducacaoOnline.Conteudos.Domain.Entities.Aula", b =>
                {
                    b.HasOne("PlataformaEducacaoOnline.Conteudos.Domain.Entities.Curso", null)
                        .WithMany("Aulas")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("PlataformaEducacaoOnline.Conteudos.Domain.ValueObjects.ConteudoProgramatico", "Conteudo", b1 =>
                        {
                            b1.Property<Guid>("AulaId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Descricao")
                                .IsRequired()
                                .HasColumnType("varchar(5000)");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("varchar(20)");

                            b1.Property<string>("Titulo")
                                .IsRequired()
                                .HasColumnType("varchar(150)");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("varchar(400)");

                            b1.HasKey("AulaId");

                            b1.ToTable("plataformaead_aulas");

                            b1.WithOwner()
                                .HasForeignKey("AulaId");
                        });

                    b.Navigation("Conteudo")
                        .IsRequired();
                });

            modelBuilder.Entity("PlataformaEducacaoOnline.Conteudos.Domain.Entities.Curso", b =>
                {
                    b.Navigation("Aulas");
                });
#pragma warning restore 612, 618
        }
    }
}
